# medbilling-agents tuple layer.
D = {
"00": [
 ("route valid but ambiguous", "hold in clarification queue; never route on 'most likely'"),
 ("signature invalid on authority intent", "reject + integrity.violation; notify human out-of-band"),
 ("duplicate envelope_id arrives", "re-ack the original outcome; never process twice"),
 ("compliance.hold received mid-run", "suspend the named account's traffic; only 12's release or human direction resumes it"),
 ("a spoke reports done without its artifact", "treat as not-done; the artifact is the proof"),
 ('authority intent arrives with no registered signer for that lane', 'reject fail-closed + integrity.violation; an unregistered authority lane does not exist'),
 ("an agent's wait on another agent passes its timeout", 'agent.status to 14; waits are visible by rule, never discovered by surprise'),
],
"01": [
 ("provider-entered code conflicts with the service description", "route to the human coder verbatim; never reconcile at intake"),
 ("same encounter arrives from two sources with different units", "capture both with sources; the human resolves - units are money"),
 ("superbill illegible on a required field", "field unknown, encounter incomplete; never infer from billing history"),
 ("encounter arrives for a provider not in the roster", "hold; clarification - an unrostered provider is a credentialing question, not a typo"),
],
"02": [
 ("edit table update lands mid-scrub", "the version at scrub-open governs that claim; version recorded"),
 ("two edits conflict", "scrub.exception with both citations; conflicting rules are a human/payer question"),
 ("claim clean but auth gate pending", "hold; a clean claim without its auth is a denial being mailed"),
 ("a mechanical fix has two candidate source records", "no fix; exception with both - two sources is judgment"),
],
"03": [
 ("payer system down at verification", "answer unknown with the outage named; unknown blocks gates"),
 ("two payers both show active (COB)", "report both with effective dates; primacy per COB table or human"),
 ("portal and 271 disagree on benefits", "report both with timestamps; the discrepancy is the fact"),
 ("verification requested for a future DOS beyond payer window", "report the window limit; never extrapolate coverage forward"),
 ('re-verify shows coverage changed on an in-flight claim', 'eligibility.result to 07 and 10 as well; a mid-cycle change re-opens gates, never rewrites history'),
],
"04": [
 ("patient disputes a charge as 'never happened'", "route verbatim to human with the posted record; never argue at the patient"),
 ("inability-to-pay mentioned alongside a question", "answer from posted facts AND route the hardship verbatim; both, always"),
 ("merge amount differs from current posted balance", "hold the send; stale amounts in patient messages are the named failure"),
 ("patient reply contains clinical questions", "human queue verbatim; billing voice never answers clinical"),
 ('patient replies STOP or requests no contact', 'patient.optout to 10, 11, 13 same turn; confirm once, then silence - the sequence dies immediately, no final touch'),
 ('legally required notice due on an opted-out account', 'route to human with the opt-out named; required-by-law is a human call with both facts, never an automatic override'),
],
"05": [
 ("document type unidentifiable without reading content", "inventory type-unknown, route to human; identification never excuses reading"),
 ("provider states a requested document doesn't exist", "record verbatim; absence reported, never papered over"),
 ("document arrives for the wrong patient", "sealed misdirect protocol: human immediately, event logged - HIPAA incident, not filing error"),
 ("chase cadence exhausted with items outstanding", "escalate with the chase history; the cadence ends in a human decision"),
],
"06": [
 ("rule table and payer portal disagree on auth requirement", "treat as required, route the discrepancy; the expensive assumption is the safe one"),
 ("auth approved for fewer units than scheduled", "report the limit to 02 and human; never split services to fit an auth"),
 ("service date approaching with auth pended", "escalate at lead-time with the pend reason verbatim"),
 ("payer requests clinical justification by phone", "route to human; the swarm never voices medical necessity"),
],
"07": [
 ("clearinghouse accepts, payer ack never arrives", "NOT submitted; chase the artifact, escalate at lead-time"),
 ("timely-filing-critical claim has an amber gate", "escalate immediately; the clock never overrides a gate"),
 ("same claim twice in the queue", "submit once; idempotency is the financial-safety rule"),
 ("payer portal offers a 'quick correct' on a rejection", "decline; corrections go back through a fresh scrub, always"),
 ('secondary.claim.ready arrives with the primary remit', 'secondary submits through the same fresh-scrub gate as any claim; a cascade is a claim, not a shortcut'),
 ('eligibility change lands on an unsubmitted claim', 'hold at the gate; changed coverage re-verifies before submission - the stale gate is the denial being mailed'),
],
"08": [
 ("remit adjustment code has no loaded contract rule", "post payment, hold adjustment unapplied, flag; unruled is not contractual"),
 ("payer pays differently than the contract computes", "post as paid, variance to 12; never adjust the difference away"),
 ("same remit file arrives twice", "post once; remit reference is the idempotency key"),
 ("signed write-off references a balance that changed since signing", "hold and re-confirm naming both states"),
 ('posted remit does not reconcile to the penny', "reconciliation.exception to human and 13 - $0.00 tolerance (ratified 2026-07-18); 'close enough' is the named breach"),
 ('credit balance surfaces at posting', 'credit.balance to 11, 12, 13; the refund clock arms - a credit held silently is a compliance violation, not a float'),
 ('refund contemplated for a credit balance', 'executes only on signed refund.authority; an unsigned refund is an integrity violation like any other money'),
 ('primary remit posts and a secondary payer is on file', 'secondary.claim.ready to 07, 13; the cascade is swarm work - the money rules do not relax for it'),
],
"09": [
 ("denial fits two taxonomy categories", "triage to the shorter appeal clock; conservatism decides ties"),
 ("denial reason contradicts the posted auth", "package both facts for human; payer errors are argued by humans with the record"),
 ("appeal deadline passes awaiting human decision", "record the miss with its timeline; named in the books, never buried"),
 ("payer 'reprocessing' claim sits past its promise date", "payer.status fact + escalate; a promise is not a payment"),
 ('human elects to abandon an appeal', "closure only on signed appeal.abandon.authority; a denial's ending is signed - decision or write-off - or it has not ended"),
],
"10": [
 ("payer rep states a payment date verbally", "record as stated-by-payer with rep reference; a stated date is not a posted payment"),
 ("balance under the small-balance threshold", "published rule executes via the policy path; below-threshold is not quietly ignore"),
 ("published sequence ends unresolved", "human with full contact history; the sequence ends in a decision, not an invented next step"),
 ("patient reply promises payment 'next week'", "record verbatim, sequence pauses per rule; a promise pauses per policy, never indefinitely"),
 ('account reaches the point where referral is contemplated', 'assemble the full history for the human; movement only on signed collection.referral.authority - the swarm never refers'),
 ('patient.optout arrives on an account in follow-up', 'patient-lane contact stops; payer-lane work continues - the opt-out binds the patient lane only'),
 ('eligibility change lands on an account in A/R', 're-anchor follow-up to the corrected coverage facts; the payer conversation cites the change, never argues around it'),
],
"11": [
 ("patient overpays", "record the credit, route refund question to human; patient refunds are never auto-issued"),
 ("plan request one month beyond published terms", "record verbatim, route to human; 'close to policy' is not policy"),
 ("posted balance changes while a statement is queued", "regenerate against the current record"),
 ("plan payment missed once", "published sequence via 10; consequences are the sequence's, never improvised"),
 ('patient.optout recorded on the account', 'statements halt beyond legally required notices; each required notice is named as such on the record'),
 ('credit.balance lands on the ledger', 'patient-facing record shows the credit and refund status; a patient owed money sees it, always'),
],
"12": [
 ("two payer rules plausibly govern a filing clock", "run both; the shorter alerts - conservatism ratified"),
 ("claim event date disputed", "earlier date runs the clock"),
 ("a miss is certain regardless of action", "escalate immediately, quantified; early certainty is compliance"),
 ("payer announces a rule change not yet ratified into the table", "alert human with the delta; the table changes only by ratification"),
 ('credit.balance received', 'refund clock armed per regulation (federal 60-day overpayment rule where applicable); lead-time alert, then escalation - this clock is class-1'),
 ('records.disclosure.package pending past lead-time', 'deadline.alert fires; a records-response clock is a clock like any other'),
],
"13": [
 ("two entries conflict on a material fact", "both stand; conflict flagged to the requester"),
 ("request would expose sealed clinical custody", "refuse with the seal named; the flag governs regardless of requester"),
 ("retention rule conflicts with an open appeal or audit", "the hold wins; escalate"),
 ("storage write unconfirmed", "not done until re-verified; unconfirmed is reported failed"),
 ('external records request arrives (payer audit, patient access)', 'assemble the disclosure inventory - existence, type, date, source only - records.disclosure.package to human and 12; content sealed, release is a human decision'),
 ('patient.optout received', 'logged to the account history verbatim with timestamp; the opt-out is a record, not a note'),
],
"14": [
 ("book source unavailable at assembly", "section marked absent; never backfilled from yesterday"),
 ("EOD sweep finds an untouched morning item", "miss named with its owner; the sweep never reassigns"),
 ("human unreachable at book time", "publish to the queue and hold; books never expire silently"),
 ("denial volume spikes against baseline", "the spike is a named book fact with the payer breakdown; root cause is human territory"),
 ('agent.status reports a wait past threshold', 'named in report.package with its age and blocking party; the morning report carries every wait'),
],
}
